[RHELC-1293] Introduce pre-commit hook to register custom markers
oamg/convert2rhel pull request #1018
Opened 2023-12-13 18:47 UTC by danmyway

* Registering the custom markers is oftentimes tedious and can lead to oversight when registering a new marker or removing a deprecated one
* this should ensure, that the configuration stays up-to-date with changes in existing markers

Jira Issues: [RHELC-1293](https://issues.redhat.com/browse/RHELC-1293)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2023-12-15 17:07 UTC, r0x0d commented on scripts/regenerate_pytest_ini.py
> +def update_pytest_ini(custom_markers, ini_file="pytest.ini"):
Since it's a ini file, maybe you could use the configparser module to deal with it? https://docs.python.org/3/library/configparser.html

2023-12-19 10:43 UTC, kokesak requested changes

2023-12-19 10:43 UTC, kokesak commented on scripts/regenerate_pytest_ini.py
> +    marker_pattern = re.compile(r"@pytest\.mark\.(?P<marker>\w+)\(?")
`^@pytest\.mark\.(\w)+` should be good enough

2023-12-19 10:43 UTC, kokesak commented on scripts/regenerate_pytest_ini.py
> +        if custom_markers:
I would move the condition to the beginning of the function:
```suggestion
    if custom_markers:
        # Nothing to do
        return

    ini_startswith = '[pytest]\ntestpaths = "convert2rhel/unit_tests"\nmarkers =\n'
    with open(ini_file, "w", encoding="utf-8") as f:
```

2024-05-15 09:54 UTC, Venefilyn commented
Can we use this instead? Means we can get rid of a lot of the integration test specific markers (and just update the naming scheme of it)
https://docs.pytest.org/en/latest/example/markers.html#automatically-adding-markers-based-on-test-names

2024-06-19 13:31 UTC, danmyway commented
> Can we use this instead? Means we can get rid of a lot of the integration test specific markers (and just update the naming scheme of it)

@Venefilyn I was looking at this option as well.
IIUIC from the code example, there needs to be a common pattern in the `nodeid` to base the conditioning on.
Our markers are dynamic by default, so I don't think we would be able to implement this.

2024-06-19 13:37 UTC, Venefilyn commented
> > Can we use this instead? Means we can get rid of a lot of the integration test specific markers (and just update the naming scheme of it)
> 
> @Venefilyn I was looking at this option as well. IIUIC from the code example, there needs to be a common pattern in the `nodeid` to base the conditioning on. Our markers are dynamic by default, so I don't think we would be able to implement this.

@danmyway but if all of the markers for integration tests are with `test_` then we have a standard already that we can go by. Or we can rename it all to start with `test_int_` for example

2024-06-19 14:01 UTC, danmyway commented
@Venefilyn ah, nvm, I got it wrong.
It looks like that adding the markers work, however we still need to register those in pytest.ini, which is where we aim with this PR

2024-06-19 15:30 UTC, Venefilyn commented
> @Venefilyn ah, nvm, I got it wrong. It looks like that adding the markers work, however we still need to register those in pytest.ini, which is where we aim with this PR

@danmyway We wouldn't need to register the automated ones with a prefix, just need to do the script as the documentation says

2024-06-20 08:29 UTC, danmyway commented
> > @Venefilyn ah, nvm, I got it wrong. It looks like that adding the markers work, however we still need to register those in pytest.ini, which is where we aim with this PR
> 
> @danmyway We wouldn't need to register the automated ones with a prefix, just need to do the script as the documentation says

@Venefilyn I've copy-pasted the example from the docs, and it still yields the warning 
```
conftest.py:65
  conftest.py:65: PytestUnknownMarkWarning: Unknown pytest.mark.interface - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    item.add_marker(pytest.mark.interface)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

```
But nvm, I'm closing this, we have found a way to just ignore the warning instead, that should be easier.

2024-06-20 08:29 UTC, closed without merging