chore: trigger testing by label instead of comment
oamg/convert2rhel pull request #1099
Opened 2024-02-15 21:16 UTC by SpyTec

Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2024-02-20 08:29 UTC, danmyway requested changes
Looks good, I would just drop some required labels here and there, but overall looks like a great addition.
Thanks, @SpyTec !

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
    require:
        label:
          present:
            - tests-run-tier1
            - tests-run-all
          absent:
            - tests-skip

```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
This should run automatically on a merge commit to main.
We don't need the label trigger here.
The same goes for the below.
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .packit.yaml
> +            - tests-skip
```suggestion
```

2024-02-20 08:29 UTC, danmyway commented on .github/label-commenter-config.yml
I would salvage the commenter, we can re-utilize it to print out what comments can be used to re-trigger tests for example, WDYT @SpyTec ?

2024-02-20 08:29 UTC, danmyway commented on .github/workflows/label-commenter.yml
I would keep this, see `.github/label-commenter-config.yml` comment.

2024-02-20 13:00 UTC, SpyTec commented on .github/label-commenter-config.yml
Oh that is a good point!

Lets make it react to label changes, I'll change that after merge freeze

2024-02-20 13:03 UTC, SpyTec commented
@danmyway for stuff where I removed 

```diff
-    manual_trigger: false
```
Should I reinstate those?

2024-02-20 14:05 UTC, danmyway commented
> Should I reinstate those?
I believe that's not necessary @SpyTec, since you also remove `manual_trigger: true`, we do not need to override the option.

2024-02-20 14:26 UTC, danmyway commented on .github/label-commenter-config.yml
Yep, I was thinking just keeping it to react to one label (e.g. `run-tests-help` or `run-tests-what`) and it could react with a concise comment with alternatives of the `/packit` comment trigger.
I will have the team vote on the label format.

2024-02-26 11:58 UTC, bookwar requested changes
Please provide the commit message which explains the intent of the change.

As I understood it you are removing the explicit comment for packit to trigger the test, but I think it won't work.

According to Packit folks the "require" feature for labels: https://packit.dev/docs/configuration#require is a "precondition to other triggers (i.e., adding/removing label doesn't trigger the job)."

So there is no trigger by label functionality in Packit.

2024-03-05 15:35 UTC, bookwar approved these changes

2024-03-07 15:38 UTC, merged