Split pytest.ini config between unit tests and integration
oamg/convert2rhel pull request #1195
Opened 2024-04-24 17:31 UTC by r0x0d

After the merge of https://github.com/oamg/convert2rhel/pull/1189, the spam of information of test setups is causing problems in github actions log rendering, as well as executing it locally/container.

This commit is intended to split the pytest.ini config file, having one for the general unit_tests configuration, and the second one for integration tests only.

Jira Issues:

-

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2024-04-24 17:34 UTC, r0x0d commented
@danmyway and @kokesak, please review it once you have some time. 

The change introduced in #1189 was causing a lot of spam in the log messages in our unit tests too. To fix this problem, I'm trying to split the pytest ini file.

2024-04-25 07:44 UTC, kokesak commented
I suggest keeping the current `pytest.ini` for the integration tests and create a separate one for the unit tests. The reason is that in your current change you have to add `-c tests/pytest.ini` to every test file we have and we'll create. It seems more straightforward and less repeated code when you add the `-c convert2rhel/unit_tests/pytest.ini` just once into the `Makefile` here https://github.com/oamg/convert2rhel/blob/main/Makefile#L32 (I suspect that you run unit tests using the make)

2024-04-25 11:29 UTC, SpyTec requested changes
Given that this changes the test calls everywhere, to avoid having to duplicate the config call, lets refactor this to a call in makefile instead. So we have a make command of pytest_int or something that has pytest -c tests/pytest.ini

Human factor will inevitably make it easier to make mistakes in the future otherwise

2024-04-25 12:03 UTC, r0x0d commented
Alright, sounds good.

2024-04-25 14:12 UTC, SpyTec approved these changes

2024-04-25 14:12 UTC, merged