WIP: Conftest refactor - satellite
oamg/convert2rhel pull request #1349
Opened 2024-08-21 11:03 UTC by kokesak

Jira Issues:

-

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2024-08-22 10:08 UTC, kokesak commented
/packit test --labels tier0

2024-08-22 13:12 UTC, kokesak commented
/packit test --labels tier0

2024-08-26 08:51 UTC, kokesak commented
/packit test --labels tier0

2024-08-26 13:58 UTC, kokesak commented on tests/ansible_collections/roles/get-test-vars/tasks/get-test-vars.yml
> +    url: https://gitlab.cee.redhat.com/oamg/convert2rhel/convert2rhel-secrets/-/raw/main/.env_sat_reg2
This we will change to `.env_sat_reg` before merging so we do not break the testing.

2024-08-26 14:17 UTC, kokesak commented
/packit test --labels tier0

2024-08-26 15:31 UTC, SerCantus requested changes
Just two small things, otherwise looking great!

2024-08-26 15:31 UTC, SerCantus commented on tests/integration/conftest.py
> +        self.key = key if key else SYSTEM_RELEASE_ENV
```suggestion
    def __init__(self, key = SYSTEM_RELEASE_ENV):
        self.shell = live_shell()
        # Key on which upon the command is selected
        self.key = key
```

2024-08-27 07:07 UTC, danmyway requested changes
Overall looks good, I like the small scope and the simplification. Just minor nitpicks.

2024-08-27 07:07 UTC, danmyway commented on tests/integration/conftest.py
> +            self.subman.remove_client_tools_repo()
A comment would be nice again.
(I know the previous fixture was lacking the comments in some places, but that's the point of the refactor, right? I mean making it better :grimacing: )

2024-08-27 08:25 UTC, kokesak commented on tests/integration/conftest.py
> +        print(match_version.group(2))
it is not needed, this was just a test if you guys do a review or just ACK it :D 
(no I somehow forgot about it when I was debugging it :D )

2024-08-27 08:25 UTC, kokesak commented on tests/integration/conftest.py
> +        print(match_version.group(2))
https://github.com/oamg/convert2rhel/pull/1349/files#r1732375125

2024-08-27 08:26 UTC, kokesak commented on tests/integration/conftest.py
> +        self.key = key if key else SYSTEM_RELEASE_ENV
good point, I change it

2024-08-27 08:33 UTC, kokesak commented on tests/integration/conftest.py
> +            self.subman.add_client_tools_repo()
Yes, we should add a comment there. I'll add it

2024-08-27 08:42 UTC, kokesak commented on tests/integration/tier0/non-destructive/enabled-repositories-after-analysis/test_enabled_repositories_after_analysis.py
> +    shell, convert2rhel, fixture_satellite, remove_repositories, rhel_repo_enabled
Sounds OK to me, if it works. I'll try to remove it

2024-08-28 06:31 UTC, kokesak commented
/packit test --labels tier0

2024-08-28 08:21 UTC, danmyway commented on tests/integration/conftest.py
> +
```suggestion
    def _curl_the_satellite_script(self, curl_command):
        assert (
            self.shell(f"{curl_command} -o {self._sat_script_location}", silent=True).returncode == 0
        ), "Failed to curl the satellite script to the machine."
        
        # This is just a mitigation of rhn-client-tools pkg obsoleting subscription-manager during upgrade
        # TODO remove when https://github.com/theforeman/foreman/pull/10280 gets merged and or foreman 3.12 is out
        # Should be around November 2024
        if "oracle" in SystemInformationRelease.distribution:
            self.shell(fr"sed -i 's/$PKG_MANAGER_UPGRADE subscription-manager/& --setopt=exclude=rhn-client-tools/' {self._sat_script_location}"
        )
```
We need to [add this](https://github.com/oamg/convert2rhel/pull/1349/files#diff-c87c5173e88bb0f60b00107f4586304f4869a976a4f998425efe3481c0db9f56L958-L964) here to beat the stubborn rhn-client-tools obsoleting subscription-manager.

2024-08-28 08:22 UTC, danmyway commented on tests/integration/tier0/non-destructive/enabled-repositories-after-analysis/test_enabled_repositories_after_analysis.py
> +    shell, convert2rhel, fixture_satellite, remove_repositories, rhel_repo_enabled
I've tried it on CentOS and it works. Additionally, the repos are already enabled there, but I would keep the enablement still just to have a generic solution without conditioning.

2024-08-28 09:36 UTC, kokesak commented on tests/integration/tier0/non-destructive/enabled-repositories-after-analysis/test_enabled_repositories_after_analysis.py
> +    shell, convert2rhel, fixture_satellite, remove_repositories, rhel_repo_enabled
seems to be working!

2024-08-28 10:27 UTC, kokesak commented
/packit build

2024-08-28 10:37 UTC, kokesak commented
/packit test --labels tier0

2024-08-28 13:08 UTC, SerCantus approved these changes
Looks great!! :rocket:

2024-08-28 14:07 UTC, danmyway approved these changes
Awesome start of a great journey ++

2024-08-28 14:07 UTC, merged