[RHELC-1725] Update rhsm custom facts
oamg/convert2rhel pull request #1395
Opened 2024-10-01 14:45 UTC by pr-watson

This PR adds the `non_default_channel` to our rhsm custom facts so we can properly record metrics on the use of EUS/ELS during conversions. 

Jira Issues:

-  [RHELC-1725](https://issues.redhat.com/browse/RHELC-1725)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [x] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2024-10-01 14:48 UTC, r0x0d commented on convert2rhel/unit_tests/toolopts/config_test.py
> -outdated_package_check_skip = false
Not related change in here

2024-10-01 14:48 UTC, r0x0d requested changes
please, revert the change on convert2rhel/unit_tests/toolopts/config_test.py

2024-10-01 14:58 UTC, pr-watson commented on convert2rhel/unit_tests/toolopts/config_test.py
> -outdated_package_check_skip = false
Thanks, it was a leftover commit

2024-10-01 14:59 UTC, pr-watson commented
> please, revert the change on convert2rhel/unit_tests/toolopts/config_test.py

Done

2024-10-04 11:21 UTC, Venefilyn commented on convert2rhel/breadcrumbs.py
> +            self.non_default_channel = "ELS"
```suggestion
        elif tool_opts.els:
            self.non_default_channel = "ELS"
```

2024-10-04 11:22 UTC, Venefilyn approved these changes

2024-10-11 11:31 UTC, r0x0d approved these changes

2024-10-11 11:56 UTC, Venefilyn commented
/packit test --labels sanity

2024-10-16 13:52 UTC, merged