Improvement of UX registration
oamg/convert2rhel pull request #247
Opened 2021-04-07 12:52 UTC by hosekadam

The piece of message "provide username and password" is not printed - it does not make sense when using RHSM with activation key + org ID
The message "Attempt x of 3..." is printed only if registration unsuccessful to not scare people as most of the time it's successful

Looks like many changes, but from me are just two: added if+else from line 99 and if+else from line 147. The other changes are made by Black code formatter.

2021-04-09 12:37 UTC, SpyTec requested changes
If possible, revert unrelated changes to avoid merge conflicts with other PRs. It also makes it difficult to browse through the changes, especially as they're all in one commit

2021-04-09 12:37 UTC, SpyTec commented on convert2rhel/subscription.py
> +            )
I'd switch this around so we have an `attempt_msg`, that way we reduce the duplication of the command (could also have a string for `Registering system by running subscription-manager command ...`, but this solution seems more readable to me). 

Also had two quotes in the logger
`"Registering system by running subscription-manager command"`
vs
`"Registering system by running subscription-manager" " command"`
```suggestion
		attempt_msg = ""
        if attempt > 0:
            attempt_mgs = "Attempt %d of %d: " % (attempt + 1, MAX_NUM_OF_ATTEMPTS_TO_SUBSCRIBE)
        loggerinst.info(
            "%sRegistering system by running subscription-manager command ...", attempt_mgs
        )
```

2021-04-09 12:37 UTC, SpyTec commented on convert2rhel/subscription.py
> +                "    ... activation key not found, username and" " password required"
```suggestion
                "    ... activation key not found, username and password required"
```

2021-04-13 07:44 UTC, ZhukovGreen commented
Maybe this is already time to introduce very lightweight pre-commit hooks for black and isort

2021-04-13 07:49 UTC, ZhukovGreen reviewed
@hosekadam unless we'll have defined black formatter as a formatted for convert2rhel (needs to be unified by pre-commit hook), you shouldn't use black for formatting existing codebase. I understand how is it painful, but otherwise this will be always making MR hard to review. However, there is good news - if you create a new module (python file) you can black format it:)
I think we have to split @fellipeh about pre-commit into smaller one. And the first hoks to introduce probably should be black and sort!

2021-04-16 15:09 UTC, bocekm requested changes

2021-04-16 15:09 UTC, bocekm commented on convert2rhel/subscription.py
> +        loggerinst.info("%sRegistering system by running subscription-manager command ...", attempt_msg)
```suggestion
        loggerinst.info("%sRegistering the system using subscription-manager ...", attempt_msg)
```

2021-05-03 12:43 UTC, bocekm approved these changes

2021-05-03 12:45 UTC, SpyTec approved these changes

2021-05-03 12:45 UTC, merged