Flagging system as converted
oamg/convert2rhel pull request #324
Opened 2021-08-05 09:02 UTC by hosekadam

Convert2RHEL shall record that the system has been converted. The information shall be stored in the /etc/migration-results file, which will be collected by Insights and sos to help the business to learn more about the number/details of migrations, and to help support engineers to identify what happened to a system.

2021-08-11 11:48 UTC, bocekm requested changes

2021-08-11 11:48 UTC, bocekm commented on convert2rhel/breadcrumbs.py
> +# is importing systeminfo good idea? It creates new instance of SystemInfo after import
> It creates new instance of SystemInfo after import

The SystemInfo instance is created just once, during the first import of systeminfo that happens in main.py. So when importing it here, the module is already loaded and the system_info variable already holds the SystemInfo instance with all data populated.

2021-08-11 11:48 UTC, bocekm commented on convert2rhel/breadcrumbs.py
> +# Copyright(C) 2016 Red Hat, Inc.
```suggestion
# Copyright(C) 2020 Red Hat, Inc.
```

2021-08-11 11:48 UTC, bocekm commented on convert2rhel/breadcrumbs.py
> +        self.executed = ""
```suggestion
        # Version of the JSON schema of the breadcrumbs file. To be changed when the content changes.
        self.version = 1
        # convert2rhel command as executed by the user including all the options
        self.executed = ""
```

2021-08-11 11:48 UTC, bocekm commented on convert2rhel/breadcrumbs.py
> +        self.run_id = None
```suggestion
        # Run ID is to be populated by Leapp only. The value should be null in the json generated by convert2rhel.
        self.run_id = None
```

2021-08-11 11:48 UTC, bocekm commented on convert2rhel/breadcrumbs.py
> +        self.timestamp = None
```suggestion
        self.activity_started = None
        self.activity_ended = None
```
@shaded-enmity can help with implementing/getting the `activity_started`.

2021-08-11 13:34 UTC, hosekadam commented on convert2rhel/breadcrumbs.py
> +# Copyright(C) 2016 Red Hat, Inc.
@bocekm 2021? :smile:

2021-08-11 14:37 UTC, bocekm commented on convert2rhel/breadcrumbs.py
> +# Copyright(C) 2016 Red Hat, Inc.
Yes :)

2021-08-11 16:39 UTC, hosekadam commented
Generated file corresponds with schema. Added intergration test.

2021-08-16 20:53 UTC, bocekm approved these changes

2021-08-17 09:39 UTC, merged