Exclude iwlax2xx-firmware dependency from the conversion in OL8
oamg/convert2rhel pull request #483
Opened 2022-04-25 16:46 UTC by r0x0d

This package is causing problems when replacing the package `iwl7260-firmware`
to it's RHEL counterpart.  The reason for that is in OL8 they splitted the
package `iwl7260-firmware` and the `iwlax2xx-firmware` the later became a
dependency of the former. In RHEL this is not true, there is only the package
`iwl7260-firmware` which contains all the files.

Jira reference (If any): https://issues.redhat.com/browse/RHELC-567
Bugzilla reference (If any):

Signed-off-by: Rodolfo Olivieri <rolivier@redhat.com>

2022-04-25 17:24 UTC, r0x0d commented
Log from the vagrant box: 

```
[root@c2r-20220425135408 ~]# rpm -q iwl7260-firmware
iwl7260-firmware-25.30.13.0-104.el8_5.1.noarch

[root@c2r-20220425135408 ~]# rpm -qi iwl7260-firmware
Name        : iwl7260-firmware
Epoch       : 1
Version     : 25.30.13.0
Release     : 104.el8_5.1
Architecture: noarch
Install Date: Mon 25 Apr 2022 17:12:56 UTC
Group       : Unspecified
Size        : 146864566
License     : Redistributable, no modification permitted
Signature   : RSA/SHA256, Mon 31 Jan 2022 14:19:51 UTC, Key ID 199e2f91fd431d51
Source RPM  : linux-firmware-20210702-104.gitd79c2677.el8_5.src.rpm
Build Date  : Fri 28 Jan 2022 18:46:13 UTC
Build Host  : ppc-061.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : http://www.kernel.org/
Summary     : Firmware for Intel(R) Wireless WiFi Link 726x/8000/9000 Series Adapters
Description :
This package contains the firmware required by the Intel wireless drivers
for Linux.  Usage of the firmware is subject to the terms and conditions
contained inside the provided LICENSE file. Please read it carefully.
```

2022-04-25 19:32 UTC, r0x0d commented
Log from the vagrant box: 

```
[root@c2r-20220425135408 ~]# rpm -q iwl7260-firmware
iwl7260-firmware-25.30.13.0-104.el8_5.1.noarch

[root@c2r-20220425135408 ~]# rpm -qi iwl7260-firmware
Name        : iwl7260-firmware
Epoch       : 1
Version     : 25.30.13.0
Release     : 104.el8_5.1
Architecture: noarch
Install Date: Mon 25 Apr 2022 17:12:56 UTC
Group       : Unspecified
Size        : 146864566
License     : Redistributable, no modification permitted
Signature   : RSA/SHA256, Mon 31 Jan 2022 14:19:51 UTC, Key ID 199e2f91fd431d51
Source RPM  : linux-firmware-20210702-104.gitd79c2677.el8_5.src.rpm
Build Date  : Fri 28 Jan 2022 18:46:13 UTC
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : http://www.kernel.org/
Summary     : Firmware for Intel(R) Wireless WiFi Link 726x/8000/9000 Series Adapters
Description :
This package contains the firmware required by the Intel wireless drivers
for Linux.  Usage of the firmware is subject to the terms and conditions
contained inside the provided LICENSE file. Please read it carefully.
```

2022-05-11 21:35 UTC, bocekm requested changes

2022-05-11 21:35 UTC, bocekm commented on tests/integration/tier1/resolve-dependency/install_dependency_packages.py
>          elif system_version.major == 8:
The test is switched off for OL 8: https://github.com/oamg/convert2rhel/commit/7920fc401fd73cf191b9d298d2fe8abde1142dc3#diff-effa0515e248da3fe738adfe9c21f2977701c9e1c8701bcc86c36acb32415a43R93.

Switch it on again by removing the `adjust` clause there.

2022-05-11 21:35 UTC, bocekm commented on tests/integration/tier1/resolve-dependency/install_dependency_packages.py
>              ]
```suggestion
            def get_system_name(system_release_content=None):
                """Return system name. For example 'Oracle Linux Server'."""
                # to be moved outside of the test_install_dependency_packages function
                name = re.search(r"(.+?)\s?(?:release\s?)?\d", self.system_release_file_content).group(1)
                return name
            system_name = get_system_name(system_release)
            if "Oracle Linux" not in system_name:
                dependency_pkgs = [
                    "python39-psycopg2-debug",  # OAMG-5239, OAMG-4944 - package not available on Oracle Linux 8                ]
            else:
                dependency_pkgs = [
                    "iwl7260-firmware",  # RHELC-567
                    "iwlax2xx-firmware",  # RHELC-567 - causing problems during the conversion on OL8
                ]
```

2022-05-11 21:35 UTC, bocekm commented on convert2rhel/special_cases.py
> +    This package causes some transaction problems while trying to replace it with it's RHEL counterpart. The reason for
```suggestion
    The iwl7260-firmware package causes a file conflict error while trying to replace it with its RHEL counterpart. The reason for
```

2022-05-11 21:35 UTC, bocekm commented on convert2rhel/special_cases.py
> +    logger.info("Removing iwlax2xx-firmware package.")
```suggestion
    logger.info("Removing the iwlax2xx-firmware package. Its content is provided by the RHEL iwl7260-firmware package.")
```

2022-05-11 21:35 UTC, bocekm commented on convert2rhel/special_cases.py
> +            _, exit_code = run_subprocess(("rpm", "-e", "--nodeps", "iwlax2xx-firmware"))
```suggestion
            _, exit_code = run_subprocess(["rpm", "-e", "--nodeps", "iwlax2xx-firmware"])
```
I know that the tuple would work when passed to subprocess.Popen, but for the sake of consistency use a list which we use everywhere else.

2022-05-12 12:22 UTC, r0x0d commented on convert2rhel/special_cases.py
> +    This package causes some transaction problems while trying to replace it with it's RHEL counterpart. The reason for
Updated the docstring.

2022-05-12 12:22 UTC, r0x0d commented on convert2rhel/special_cases.py
> +    logger.info("Removing iwlax2xx-firmware package.")
done.

2022-05-12 15:12 UTC, r0x0d commented on plans/tier1.fmf
>      enabled: false
Well noted! Fixed now.

2022-05-12 19:02 UTC, bocekm approved these changes

2022-05-16 12:10 UTC, bocekm commented
The `tier1/custom_repos` integration test on OL 7 failed with:
`https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-logos-70.7.0-1.0.7.el7.noarch.rpm: [Errno 14] curl#35 - "Peer reports it experienced an internal error."`
Since this PR involves OL 8 and the test failure is infrastructure-related, I'm merging the PR.

2022-05-16 12:10 UTC, merged