[RHELC-399] Add test description
oamg/convert2rhel pull request #694
Opened 2023-01-11 13:44 UTC by danmyway

* add description for tests changed-grub-file, os-release-removal and method directory

Signed-off-by: Daniel Diblik <ddiblik@redhat.com>

Jira Issue: [RHELC-399](https://issues.redhat.com/browse/RHELC-399)

Checklist
- [x] PR meets acceptance criteria specified in the Jira issue
- [ ] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending`

2023-01-12 12:56 UTC, SpyTec commented on tests/integration/tier1/os-release-removal/main.fmf
> +summary: Removed /etc/os-release
I'd say we should be future tens of what we will do rather than what happened
```suggestion
summary: Remove /etc/os-release
```

2023-01-16 11:10 UTC, kokesak requested changes

2023-01-16 11:10 UTC, kokesak commented on tests/integration/tier1/method/main.fmf
> +    Tested methods: satellite, RHSM, non-EUS RHSM, activation key.
```suggestion
    Tested methods: satellite, RHSM, non-EUS RHSM, activation key, and custom repos.
```

2023-01-31 09:47 UTC, SpyTec approved these changes

2023-01-31 12:01 UTC, kokesak commented on tests/integration/tier1/changed-grub-file/main.fmf
> +summary: Changed grub file
Just this one still remains

2023-02-02 12:14 UTC, r0x0d commented
pre-commit.ci run

2023-02-03 13:56 UTC, danmyway commented on tests/integration/tier1/changed-grub-file/main.fmf
> +summary: Changed grub file
My bad, done @kokesak

2023-02-06 09:45 UTC, danmyway commented
/packit test

2023-02-06 12:11 UTC, r0x0d approved these changes

2023-02-07 08:09 UTC, kokesak approved these changes

2023-02-07 08:10 UTC, merged