Fix failing system_up_to_date test
oamg/convert2rhel pull request #755
Opened 2023-03-01 12:50 UTC by danmyway

* sometimes the test for non-latest kernel inhibition fails, due to `kvm` kernel module getting tainted in the process of downgrading the kernel package on Oracle Linux 8.7
* for the sake of the test, detect if `kvm` module is marked tainted and remove it (and `kvm_intel` as dependent module)

2023-03-02 20:38 UTC, danmyway commented
/packit test

2023-03-07 09:31 UTC, danmyway commented
/packit test

2023-03-07 11:13 UTC, danmyway commented
/packit test

2023-04-13 07:48 UTC, kokesak requested changes

2023-04-13 07:48 UTC, kokesak commented on tests/integration/tier1/system-up-to-date/test_non_latest_kernel_inhibitor.py
> +        shell("rmmod kvm_intel && rmmod kvm")
I would separate those commands into two. If the `kvm_intel` module is not present (probably due to its name, it is only available on x86_64 architectures) then the `kvm` will not get removed.
Another option would be to detect the running arch and if it is `x86_64` then try also to removing the `kvm_intel`

2023-08-03 21:10 UTC, danmyway commented
The issue is not popping up anymore, closing this Pull Request.

2023-08-03 21:10 UTC, closed without merging