Move report to after rollack
oamg/convert2rhel pull request #798
Opened 2023-04-04 17:26 UTC by abadger

Move when we print the report.
    
    There are three separate cases where we want to print the report:
    
    1) For the user to review before confirming that they want to continue
       past the PONR.  This is where in the code's workflow that the
       happening.
    2) For the user to fix things when a conversion failed prior to the PONR
    3) For the user to see whether the machine is ready to convert (analyze
       report).
    
    Each of these three cases wants to print the report at a different point
    in the process:
    
    (1) Just before confirmation that the user should go past the PONR
    (2) After rollback, just before failing with return code 1
    (3) After rollback, just before returning with return code 0

Output for a conversion that fails before this change:
* https://toshio.fedorapeople.org/convert2rhel/pre-check-2023-04-04.log

Output for a conversion that fails after this change:
* https://toshio.fedorapeople.org/convert2rhel/pre-check-moved-report-2023-04-04.log

Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2023-04-05 12:49 UTC, r0x0d requested changes
The change looks good, the only thing is that the header that is only present in one report, not in the others. 

The output looks a bit strange without it. It is hard to identify where the report starts and where the previous output finishes.

2023-04-05 23:20 UTC, abadger commented on convert2rhel/main.py
> -        loggerinst.task("Conversion analysis report")
Thanks!  Fixed by moving the loggerinst.task() call into report.summary()

2023-04-06 12:25 UTC, r0x0d commented on convert2rhel/main.py
>              # report.summary has already output more detailed information above
Comment is wrong here as we moved the report to be after this

2023-04-06 12:27 UTC, r0x0d approved these changes
Just one minor comment that I would not block the PR on that.

2023-04-06 16:28 UTC, r0x0d approved these changes

2023-04-06 18:58 UTC, merged