[RHELC-901] Allow username and organization in the config file
oamg/convert2rhel pull request #826
Opened 2023-05-10 18:33 UTC by r0x0d

Allow the username and organization to be used in the config file as a secure way of using the RHSM credentials duirng the conversion.

Previously, only the password and activation key were used and parsed in the config file.

Jira Issues: [RHELC-901](https://issues.redhat.com/browse/RHELC-901)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2023-05-10 18:34 UTC, r0x0d commented
@bocekm am I missing something here? Not sure if I should do other type of verifications other than username and org being passed in the config file and CLI, as is the case for activation_key and password. 

Let me know on what I could change here.

2023-05-10 19:40 UTC, bocekm commented
> @bocekm am I missing something here? Not sure if I should do other type of verifications other than username and org being passed in the config file and CLI, as is the case for activation_key and password.

The question is better suited for @abadger and @hosekadam who were involved the most in the introduction of the config file (https://github.com/oamg/convert2rhel/pull/451).

2023-05-11 12:43 UTC, abadger requested changes
One change (n toolopts.py) that I think needs to be done and a few small suggestions for the tests.

2023-05-11 12:45 UTC, r0x0d commented on convert2rhel/toolopts.py
> +        if (config_opts.username or config_opts.org) and (parsed_opts.username or parsed_opts.org):
Ah, alright! It makes sense! 

I wsa wondering if username + org would cause a problem, but will separate the checks then.

2023-05-11 12:53 UTC, r0x0d commented on convert2rhel/toolopts.py
> +        if (config_opts.username or config_opts.org) and (parsed_opts.username or parsed_opts.org):
separated and done!

2023-05-11 12:58 UTC, r0x0d commented on convert2rhel/unit_tests/toolopts_test.py
> +        ),
done! 

I think it makes sense to split each parameter and test the low prior value for them

2023-05-15 12:36 UTC, SpyTec approved these changes
Code itself LGTM, not tested locally

2023-05-19 15:25 UTC, abadger approved these changes
Changes have been made.  Approved!

2023-05-25 15:39 UTC, danmyway approved these changes

2023-05-25 15:39 UTC, merged