[DRAFT] Try official Oracle Linux AWS AMIs
oamg/convert2rhel pull request #845
Opened 2023-05-29 13:55 UTC by danmyway

* as per guidance from https://forums.oracle.com/ords/apexds/post/launch-an-oracle-linux-instance-in-aws-9462 it is possible to launch an official Oracle Linux on AWS
* the images were successfully deployed on Testing Farm staging and production, try using in pipeline
* add post install script to enable root login

Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2023-05-29 16:01 UTC, danmyway commented
/packit test

2023-06-02 10:49 UTC, danmyway commented
/packit test

2023-08-07 11:38 UTC, kokesak commented
/packit test --labels tier0

2023-08-09 14:21 UTC, danmyway commented
/packit test --labels tier0

2023-09-05 14:55 UTC, kokesak requested changes

2023-09-05 14:55 UTC, kokesak commented on .packit.yaml
> +  identifier: "tier0-destructive-centos"
```suggestion
  identifier: "tier0-destructive-oraclelinux-8"
```

2023-09-05 15:03 UTC, danmyway commented on .packit.yaml
> +  identifier: "tier0-destructive-centos"
done, thx

2023-09-05 15:03 UTC, danmyway commented on .packit.yaml
> +  identifier: "tier0-destructive-centos"
done, good catch

2023-09-05 15:08 UTC, kokesak approved these changes
LGTM!, if the tests are fine let's merge it!

2023-09-05 17:13 UTC, merged