try uefi
oamg/convert2rhel pull request #950
Opened 2023-10-09 08:40 UTC by kokesak

Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

2023-10-20 12:04 UTC, kokesak commented
There is some issue when listing tmt tests.

Running the `multiple-nic` test manually  is ok:
c7: http://artifacts.osci.redhat.com/testing-farm/3de4f91d-a29e-4fa8-9bf3-dd4f678c1053
c8: http://artifacts.osci.redhat.com/testing-farm/0a30cf20-1e37-46f6-91eb-d03365d6d4ec

I'm gonna take a look on why it fails here

2023-10-20 15:24 UTC, kokesak commented
> There is some issue when listing tmt tests.
> 
> Running the `multiple-nic` test manually is ok: c7: http://artifacts.osci.redhat.com/testing-farm/3de4f91d-a29e-4fa8-9bf3-dd4f678c1053 c8: http://artifacts.osci.redhat.com/testing-farm/0a30cf20-1e37-46f6-91eb-d03365d6d4ec
> 
> I'm gonna take a look on why it fails here

The fix: https://github.com/oamg/convert2rhel/pull/971

2023-10-23 14:20 UTC, danmyway requested changes
Just some metadata rephrasing, other than that looks good! 
Thanks!

2023-10-23 14:20 UTC, danmyway commented on tests/integration/tier1/destructive/multiple-nic/main.fmf
> +  pytest -svv
```suggestion
summary+: |
  Conversion with multiple NICs

description+: |
  Verify, that it's possible to do a full conversion of the system 
  that has more than one NIC connected and running.
  The test uses RHSM as a conversion method.

test: |
  pytest -svv
```

2023-10-23 14:52 UTC, kokesak commented on tests/integration/tier1/destructive/multiple-nic/main.fmf
> +  pytest -svv
Thanks, I changed it.

2023-10-25 07:48 UTC, danmyway approved these changes
LGTM, thanks!

2023-10-25 16:30 UTC, merged